version: '3.4'

services:
  mssql:
    container_name: mssql
    user: root
    environment:
     - SA_PASSWORD=RS2MADproject123
     - ACCEPT_EULA=Y
    restart: always
    ports:
     - "1433:1433"
    volumes:
     - mssql_data:/var/opt/mssql/data

  spacesdb:
    container_name: spacesdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  imagesdb:
    container_name: imagesdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - imagesmongo_data:/data/db

  advertising.api:
    container_name: advertising.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "GrpcSettings:SpacesUri=http://spaces.grpc"
    depends_on:
     - spaces.grpc
    ports:
      - "8000:80"

  spaces.api:
    container_name: spaces.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://spacesdb:27017"
      - "GrpcSettings:ImagesUri=http://cdn.grpc"
    depends_on:
      - spacesdb
      - cdn.grpc
    ports:
      - "8001:80"

  spaces.grpc:
    container_name: spaces.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://spacesdb:27017"
      - "GrpcSettings:ImagesUri=http://cdn.grpc"
    depends_on:
      - spacesdb
      - cdn.grpc 
    ports:
      - "8002:80"

  cdn.api:
    container_name: cdn.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CDNDbSettings:ConnectionString=mongodb://spacesdb:27017
    depends_on:
      - spacesdb
    ports:
      - "7001:80"

  cdn.grpc:
    container_name: cdn.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CDNDbSettings:ConnectionString=mongodb://spacesdb:27017
    depends_on:
      - spacesdb
    ports:
      - "7002:80"

  identityserver.api:
    container_name: identityserver.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssql
    ports:
      - "4000:80"

