version: '3.4'

services:
  mssql:
    container_name: mssql
    environment:
     - SA_PASSWORD = RS2MADproject123
     - ACCEPT_EULA = Y
    restart: always
    ports:
     - "1433:1433"
    volumes:
     - mssql_data:/var/opt/mssql/data 

  spacesdb:
    container_name: spacesdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  advertising.api:
    container_name: advertising.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "GrpcSettings:SpacesUri=http://spaces.grpc"
    depends_on:
     - spaces.grpc
    ports:
      - "8000:80"

  spaces.api:
    container_name: spaces.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://spacesdb:27017"
    depends_on:
      - spacesdb
    ports:
      - "8001:80"


  spaces.grpc:
    container_name: spaces.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://spacesdb:27017"
    depends_on:
      - spacesdb
    ports:
      - "8002:80"


  identityserver.api:
    container_name: identityserver.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssql
    ports:
      - "8003:80"

